server:
  port: 8080
logging:
  config: ./logback-spring.xml
spring:
  application:
    name: spring-config-example  #对应spring-config-file 下spring-config-example 配置文件
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    bus:
      enabled: true
      refresh:
        enabled: true
#spring.config.import=optional:configserver:http://root:s3cr3t@localhost:8888

     